baseURL: https://ericji.net
languageCode: en-us
title: Eric's Blog
theme: PaperMod
params:
    homeInfoParams:
        Title: Hi, I'm Eric.
        Content: Have a good day!
    socialIcons:
        - name: github
          url: "https://github.com/PearlyWave"